In [13]:
import numpy as np
import pandas as pd
import math as mt
import matplotlib.pyplot as plt
import torch

In [14]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
t=[11,12,13,14,15]

In [15]:
c=a+b+t
c

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [16]:
d=torch.tensor(c)
d

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
d.reshape(3,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [18]:
e=torch.arange(48)

In [19]:
e

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [20]:
e.reshape(4,6,2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31],
         [32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39],
         [40, 41],
         [42, 43],
         [44, 45],
         [46, 47]]])

In [21]:
e.argmin

<function Tensor.argmin>

In [22]:
e

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [24]:
e=e.reshape(4,6,2)

In [37]:
e
s=torch.arange(48, end=187)
s=s.reshape(4,6,2)

RuntimeError: shape '[4, 6, 2]' is invalid for input of size 139

In [33]:
e.diagonal_scatter(src=s)

RuntimeError: expected src to have a size equal to the slice of self. src size = [32], slice size = [2, 4]

In [32]:
s

tensor([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [36]:
79-48

31