In [1]:
Name="ABCDE"

In [2]:
Name.find("B") 

1

In [3]:
'1:2,3:4'.split(':')

['1', '2,3', '4']

In [4]:
for i in range(1,5): 

      if (i!=2):  

          print(i)

1
3
4


In [6]:
class Rectangle(object): 

    def __init__(self,width=2,height =3,color='r'):

        self.height=height 

        self.width=width 

        self.color=color 

    def drawRectangle(self): 

        import matplotlib.pyplot as plt 

        plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color)) 

        plt.axis('scaled')
        plt.show()

In [7]:
import numpy as np

In [8]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a/b 

/var/folders/8n/93cxfvlx1xb92d84k356n8qc0000gn/T/ipykernel_45804/2082349209.py:5: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 0., inf,  0., inf,  0.])

In [9]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a/b 

/var/folders/8n/93cxfvlx1xb92d84k356n8qc0000gn/T/ipykernel_45804/2082349209.py:5: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 0., inf,  0., inf,  0.])

In [10]:
a=np.array([1,1,1,1,1,])

In [11]:
a+10

array([11, 11, 11, 11, 11])

In [12]:
11-a

array([10, 10, 10, 10, 10])

In [13]:
a+1

array([2, 2, 2, 2, 2])

In [14]:
a=np.array([1,2,1,1,1])


In [15]:
a+10

array([11, 12, 11, 11, 11])